title: Mountainwerks
description: >
  Mountain climbing and armchair philosophy
url: "https://mountainwerks.org/"
paginate:	2 # The number of posts to show per page on your homepage
name: "Mike Stanton"
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: cma
    values:
      layout: post
  - scope:
      path: ""
      type: blog
    values:
      layout: post

collections:
  cma:
    output: true
  blog:
    output: true

kramdown:
  parse_block_html: true
gems:
  [jekyll-paginate]
