# Site
title:              Mountainwerks
bio:                'Climbing and hiking in the Alps.'
description:        "Climbing and hiking in the Alps."
# On the web site, /cmaimages contains static mountain images.
# In the output _site directory, I've set it to be a symbolic link to
# the root of that separate image repository. The keep_files declaration
# below means that the link won't be destroyed on rebuild. This is only
# necessary for previews, since propping to the main site doesn't destroy
# the cmaimages directory.
keep_files:         [cmaimages]
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mountainwerks.org" # the base hostname & protocol for your site
name: "Mike of the Mountains"

collections:
  cma:
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:
- scope:
    path: ""
    type: cma
  values:
    layout: post
    permalink: "/cma/:path.html"


# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  parse_block_html: false
  parse_span_html:  false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mountainwerks

# Social
analytics-id:       "default"
github:             ripsawridge

# personal
location:           Munich, Germany
email:              ripsawridge@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
