title: Mountainwerks
description: >
  Mountain climbing and armchair philosophy
baseurl: "/site"
url: "https://mountainwerks.org/"
paginate:	2 # The number of posts to show per page on your homepage
name: "Mike Stanton"
markdown: kramdown
permalink: none

defaults:
  - scope:
      path: ""
      type: cma
    values:
      layout: post
   
collections:
  cma:
    output: true

kramdown:
  parse_block_html: true
gems:
  [jekyll-paginate]
